<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OverWatchELD.VtcBot</AssemblyName>
    <StartupObject>OverWatchELD.VtcBot.Program</StartupObject>
    <DefaultItemExcludes>$(DefaultItemExcludes);OverWatchELD.Hub/**;OverWatchELD.Hub\**;Program_SplitExample.cs;**/Program_SplitExample.cs;**\Program_SplitExample.cs</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
  <PackageReference Include="Npgsql" Version="8.0.6" />
</ItemGroup>

  <ItemGroup>
    <Compile Remove="OverWatchELD.Hub/**/*.cs" />
    <Compile Remove="OverWatchELD.Hub\**\*.cs" />
    <Compile Remove="Program_SplitExample.cs" />
    <None Remove="OverWatchELD.Hub/**/*" />
    <None Remove="OverWatchELD.Hub\**\*" />
    <Content Remove="OverWatchELD.Hub/**/*" />
    <Content Remove="OverWatchELD.Hub\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.16.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
  </ItemGroup>

</Project>
